version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - .local.env # Load environment variables from the .env file

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=dev
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - ./backend:/app
    command: ["npm", "run", "local:start"] # Run the backend with npm script

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ broker
      - "15672:15672" # RabbitMQ UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  consumer:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - NODE_ENV=dev
      - RABBITMQ_URL=amqp://rabbitmq
    volumes:
      - ./backend:/app
    command: ["node", "consumer.js"] # Override CMD to run consumer.js
