const FETCH_ALL_STORIES = "FETCH_ALL_STORIES";
const FETCH_USER_STORIES = "FETCH_USER_STORIES";
const FETCH_ALL_TAGS = "FETCH_ALL_TAGS";
const FETCH_STORIES_BY_TAG = "FETCH_STORIES_BY_TAG";
const CREATE_STORY = "CREATE_STORY";
const UPDATE_STORY = "UPDATE_STORY";
const DELETE_STORY = "DELETE_STORY";
const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT";
const OPEN_DASHBOARD = "OPEN_DASHBOARD";
const FETCH_PROFILE = "FETCH_PROFILE";

export {
    FETCH_ALL_STORIES,
    FETCH_USER_STORIES,
    FETCH_ALL_TAGS,
    FETCH_STORIES_BY_TAG,
    CREATE_STORY,
    UPDATE_STORY,
    DELETE_STORY,
    AUTHENTICATION,
    LOGOUT,
    OPEN_DASHBOARD,
    FETCH_PROFILE
}